spring.application.name=ykd
#高德天气查询
gaode.key=38be8ea8e5cf8a0903b7e3b8ef236e61
#ai
spring.ai.openai.api-key=${DEEPSEEK_KEY:}                                                                             
spring.ai.openai.base-url=https://api.deepseek.com                                                                    
spring.ai.openai.chat.options.model=deepseek-chat  