spring.application.name=weather-query

# 心知天气 API 配置
weather.api.url=https://api.seniverse.com/v3/weather/now.json
weather.api.public-key=P7KOXeLWc93vXyd4m
weather.api.private-key=SGR2KR3Mz6Ro-NqTJ
weather.api.ttl=1800

# 服务端口
server.port=8080
